spring:
    application:
        name: topjob
    #config database
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/data_topjob
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    #config upload file
    servlet:
        multipart:
            max-file-size: 50MB
            max-request-size: 50MB
    ##config start page = =1
    data:
        web:
            pageable:
                one-indexed-parameters: true
    #config email với gmail
    mail:
        host: smtp.gmail.com
        port:   587
        username: ngoduy07142003@gmail.com
        password: kohpobgklfcqyisg
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true
jwt:
  base64-secret: zfoKGWEeXmzc/1FqWzChhgMH2WHtfWdK7idp5Hrlae06seBf8LWMw0Wg07s2f/C9b24sPML1VahqXopnxgq9ZA==
  #config thời gian hết hạn access-token và refresh-token
  access-token-validity-in-seconds: 86400
  refresh-token-validity-in-seconds: 864000 


